CREATE TABLE public.orders (
    id SERIAL PRIMARY KEY,
    order_id VARCHAR(20) NOT NULL UNIQUE,
    organization_id BIGINT NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    order_date DATE NOT NULL,
    delivery_date DATE,
    total_amount NUMERIC(12,2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    order_status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    shipping_address TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

-- Indexes
CREATE INDEX idx_orders_organization_id ON public.orders (organization_id);




CREATE TABLE public.organizations (
    id BIGSERIAL PRIMARY KEY,
    org_name VARCHAR(255) NOT NULL,
    constitution VARCHAR(255) NOT NULL,
    address1 VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    zip VARCHAR(255) NOT NULL,
    gst VARCHAR(255),
    pan VARCHAR(255),
    drug1 VARCHAR(255),
    drug2 VARCHAR(255),
    rep_fname VARCHAR(255) NOT NULL,
    rep_lname VARCHAR(255) NOT NULL,
    rep_email VARCHAR(255) NOT NULL,
    rep_aadhar VARCHAR(255) NOT NULL,
    rep_number VARCHAR(255) NOT NULL,
    web_uname VARCHAR(255) NOT NULL,
    web_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(255) DEFAULT 'processing'
);



CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE
);




CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);
